
ALTER TABLE public.team_sponsors
  ADD COLUMN IF NOT EXISTS contact_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_email TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS divulgation_date TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS payment_date TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_description TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'dinheiro',
  ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
